version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: md-doc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  md-doc:
    image: md-doc
    container_name: md-doc
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - mysql